### ISSUE TITLE
input_channels paramters?

### ISSUE THREAD

**Issue by AI-Hunter** [hustvl/HAIS#16]
It makes little confused about the value of the input_channel. Is it 3 or 6 (xyzrgb)?

```
DATA:
  data_root: /home/khalilullah/HAIS_spconv12_cuda112py110/dataset
  dataset: scannetv2
  filename_suffix: _inst_nostuff.pth

  classes: 20
  ignore_label: -100

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50 -> voxel_size 0.02m
  batch_size: 1
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean
```
Anyone give the answer please?
Thanks
